[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Lucas Bombarda <lucas@devdock.com.br>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
